# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-09 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.IntegerField()),
                ('by_user', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'comment_tab',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('photo_url', models.CharField(blank=True, max_length=100)),
                ('categories', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['-date'],
                'db_table': 'event_tab',
            },
        ),
        migrations.CreateModel(
            name='EventCategoryMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('category_name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'event_category_tab',
            },
        ),
        migrations.CreateModel(
            name='EventLikeMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'event_like_tab',
            },
        ),
        migrations.CreateModel(
            name='EventParticipantMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'event_participant_tab',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('salt', models.CharField(max_length=20)),
                ('role', models.IntegerField()),
            ],
            options={
                'db_table': 'user_tab',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=[b'username'], name='user_tab_usernam_0cfa56_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipantmap',
            index=models.Index(fields=[b'event_id'], name='event_parti_event_i_690f10_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlikemap',
            index=models.Index(fields=[b'event_id'], name='event_like__event_i_eb03d9_idx'),
        ),
        migrations.AddIndex(
            model_name='eventcategorymap',
            index=models.Index(fields=[b'category_name', b'event_id'], name='event_categ_categor_8c6086_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=[b'-date'], name='event_tab_date_18491a_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=[b'event_id'], name='comment_tab_event_i_9c8d54_idx'),
        ),
    ]
