# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-01 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='eventcategorymap',
            name='event_categ_categor_42cac7_idx',
        ),
        migrations.AddField(
            model_name='event',
            name='photo_url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='eventcategorymap',
            index=models.Index(fields=[b'category_id', b'event_id'], name='event_categ_categor_43078c_idx'),
        ),
    ]
