# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-03 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0002_auto_20190701_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
