# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-03 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0003_auto_20190703_0950'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
